name: lionfish-app
services:
- name: backend
  source_dir: /server
  github:
    repo: Mazzlabs/Mazzlabs.works
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT mazzlabs_api.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  - path: /admin
  health_check:
    http_path: /api/health/
  envs:
  - key: DEBUG
    scope: RUN_TIME
    value: "False"
  - key: MONGODB_URI
    scope: RUN_TIME
    value: mongodb+srv://doadmin:3FHt5081KM9ykr47@db-mongodb-nyc3-90149-031b6365.mongo.ondigitalocean.com/admin?replicaSet=db-mongodb-nyc3-90149&tls=true&authSource=admin
    type: SECRET
  - key: SECRET_KEY
    scope: RUN_TIME
    value: django-production-secret-key-change-me
    type: SECRET
  - key: ALLOWED_HOSTS
    scope: RUN_TIME
    value: lionfish-app.ondigitalocean.app,localhost,127.0.0.1
- name: frontend
  source_dir: /client
  github:
    repo: Mazzlabs/Mazzlabs.works
    branch: main
  build_command: npm ci && npm run build
  run_command: npx serve -s build -p $PORT
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: https://lionfish-app.ondigitalocean.app
